### PR TITLE
Support for Bitbucket

### PR DESCRIPTION
**Pull request by dgreenbean**
This change simply updates the plugin to support Bitbucket.  It includes only the minimal changes necessary.  A more complete change might involve changing the namespaces and similar.

### CODE REVIEW

**Comment by wparad** [comment]
I didn't know this was changing, thanks for for the pull request update.  I haven't had the chance to look into the Travis failure yet, did you have any insights there?  Seems like it could be a simple POM failure.

**Comment by dgreenbean** [comment]
I think it just needs JDK 1.8.  I had a similar problem when I first tried
to build it locally.
בתאריך 24 בפבר 2016 18:05,‏ "Warren Parad" <notifications@github.com> כתב:

**Comment by wparad** [comment]
That seems to solve it, can you add in
```
jdk:
  - oraclejdk8
```
to the `.travis.yml` file according to [Docs](https://docs.travis-ci.com/user/languages/java#Testing-Against-Multiple-JDKs) under tha language flag?

**Comment by wparad** [comment]
I'm going to create a new major release with this change, 2.0.  Once the build passes and the merge is in.

**Comment by wparad** [comment]
Cycling PR to get a rebuild against the latest version with #11.

**Pull request merged**
